// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Printf from "bs-platform/lib/es6/printf.js";

console.log(Printf.sprintf(/* Format */{
          _0: {
            TAG: /* String_literal */11,
            _0: "hello world",
            _1: /* End_of_format */0
          },
          _1: "hello world"
        }));

export {
  
}
/*  Not a pure module */
